// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spacemesh/v1/activation_types.proto

// Protobuf Java Version: 3.25.1
package spacemesh.v1;

public final class ActivationTypes {
  private ActivationTypes() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:spacemesh.v1.GetRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes id = 1;</code>
     * @return The id.
     */
    com.google.protobuf.ByteString getId();
  }
  /**
   * Protobuf type {@code spacemesh.v1.GetRequest}
   */
  public static final class GetRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:spacemesh.v1.GetRequest)
      GetRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetRequest.newBuilder() to construct.
    private GetRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetRequest() {
      id_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return spacemesh.v1.ActivationTypes.internal_static_spacemesh_v1_GetRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return spacemesh.v1.ActivationTypes.internal_static_spacemesh_v1_GetRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              spacemesh.v1.ActivationTypes.GetRequest.class, spacemesh.v1.ActivationTypes.GetRequest.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString id_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getId() {
      return id_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!id_.isEmpty()) {
        output.writeBytes(1, id_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!id_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, id_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof spacemesh.v1.ActivationTypes.GetRequest)) {
        return super.equals(obj);
      }
      spacemesh.v1.ActivationTypes.GetRequest other = (spacemesh.v1.ActivationTypes.GetRequest) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static spacemesh.v1.ActivationTypes.GetRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static spacemesh.v1.ActivationTypes.GetRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static spacemesh.v1.ActivationTypes.GetRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static spacemesh.v1.ActivationTypes.GetRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static spacemesh.v1.ActivationTypes.GetRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static spacemesh.v1.ActivationTypes.GetRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static spacemesh.v1.ActivationTypes.GetRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static spacemesh.v1.ActivationTypes.GetRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static spacemesh.v1.ActivationTypes.GetRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static spacemesh.v1.ActivationTypes.GetRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static spacemesh.v1.ActivationTypes.GetRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static spacemesh.v1.ActivationTypes.GetRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(spacemesh.v1.ActivationTypes.GetRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code spacemesh.v1.GetRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:spacemesh.v1.GetRequest)
        spacemesh.v1.ActivationTypes.GetRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return spacemesh.v1.ActivationTypes.internal_static_spacemesh_v1_GetRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return spacemesh.v1.ActivationTypes.internal_static_spacemesh_v1_GetRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                spacemesh.v1.ActivationTypes.GetRequest.class, spacemesh.v1.ActivationTypes.GetRequest.Builder.class);
      }

      // Construct using spacemesh.v1.ActivationTypes.GetRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return spacemesh.v1.ActivationTypes.internal_static_spacemesh_v1_GetRequest_descriptor;
      }

      @java.lang.Override
      public spacemesh.v1.ActivationTypes.GetRequest getDefaultInstanceForType() {
        return spacemesh.v1.ActivationTypes.GetRequest.getDefaultInstance();
      }

      @java.lang.Override
      public spacemesh.v1.ActivationTypes.GetRequest build() {
        spacemesh.v1.ActivationTypes.GetRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public spacemesh.v1.ActivationTypes.GetRequest buildPartial() {
        spacemesh.v1.ActivationTypes.GetRequest result = new spacemesh.v1.ActivationTypes.GetRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(spacemesh.v1.ActivationTypes.GetRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof spacemesh.v1.ActivationTypes.GetRequest) {
          return mergeFrom((spacemesh.v1.ActivationTypes.GetRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(spacemesh.v1.ActivationTypes.GetRequest other) {
        if (other == spacemesh.v1.ActivationTypes.GetRequest.getDefaultInstance()) return this;
        if (other.getId() != com.google.protobuf.ByteString.EMPTY) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                id_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString id_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getId() {
        return id_;
      }
      /**
       * <code>bytes id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>bytes id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:spacemesh.v1.GetRequest)
    }

    // @@protoc_insertion_point(class_scope:spacemesh.v1.GetRequest)
    private static final spacemesh.v1.ActivationTypes.GetRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new spacemesh.v1.ActivationTypes.GetRequest();
    }

    public static spacemesh.v1.ActivationTypes.GetRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetRequest>() {
      @java.lang.Override
      public GetRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GetRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public spacemesh.v1.ActivationTypes.GetRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:spacemesh.v1.GetResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.spacemesh.v1.Activation atx = 1;</code>
     * @return Whether the atx field is set.
     */
    boolean hasAtx();
    /**
     * <code>.spacemesh.v1.Activation atx = 1;</code>
     * @return The atx.
     */
    spacemesh.v1.Types.Activation getAtx();
    /**
     * <code>.spacemesh.v1.Activation atx = 1;</code>
     */
    spacemesh.v1.Types.ActivationOrBuilder getAtxOrBuilder();

    /**
     * <code>.spacemesh.v1.MalfeasanceProof malfeasance_proof = 2;</code>
     * @return Whether the malfeasanceProof field is set.
     */
    boolean hasMalfeasanceProof();
    /**
     * <code>.spacemesh.v1.MalfeasanceProof malfeasance_proof = 2;</code>
     * @return The malfeasanceProof.
     */
    spacemesh.v1.Types.MalfeasanceProof getMalfeasanceProof();
    /**
     * <code>.spacemesh.v1.MalfeasanceProof malfeasance_proof = 2;</code>
     */
    spacemesh.v1.Types.MalfeasanceProofOrBuilder getMalfeasanceProofOrBuilder();
  }
  /**
   * Protobuf type {@code spacemesh.v1.GetResponse}
   */
  public static final class GetResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:spacemesh.v1.GetResponse)
      GetResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetResponse.newBuilder() to construct.
    private GetResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return spacemesh.v1.ActivationTypes.internal_static_spacemesh_v1_GetResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return spacemesh.v1.ActivationTypes.internal_static_spacemesh_v1_GetResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              spacemesh.v1.ActivationTypes.GetResponse.class, spacemesh.v1.ActivationTypes.GetResponse.Builder.class);
    }

    private int bitField0_;
    public static final int ATX_FIELD_NUMBER = 1;
    private spacemesh.v1.Types.Activation atx_;
    /**
     * <code>.spacemesh.v1.Activation atx = 1;</code>
     * @return Whether the atx field is set.
     */
    @java.lang.Override
    public boolean hasAtx() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.spacemesh.v1.Activation atx = 1;</code>
     * @return The atx.
     */
    @java.lang.Override
    public spacemesh.v1.Types.Activation getAtx() {
      return atx_ == null ? spacemesh.v1.Types.Activation.getDefaultInstance() : atx_;
    }
    /**
     * <code>.spacemesh.v1.Activation atx = 1;</code>
     */
    @java.lang.Override
    public spacemesh.v1.Types.ActivationOrBuilder getAtxOrBuilder() {
      return atx_ == null ? spacemesh.v1.Types.Activation.getDefaultInstance() : atx_;
    }

    public static final int MALFEASANCE_PROOF_FIELD_NUMBER = 2;
    private spacemesh.v1.Types.MalfeasanceProof malfeasanceProof_;
    /**
     * <code>.spacemesh.v1.MalfeasanceProof malfeasance_proof = 2;</code>
     * @return Whether the malfeasanceProof field is set.
     */
    @java.lang.Override
    public boolean hasMalfeasanceProof() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.spacemesh.v1.MalfeasanceProof malfeasance_proof = 2;</code>
     * @return The malfeasanceProof.
     */
    @java.lang.Override
    public spacemesh.v1.Types.MalfeasanceProof getMalfeasanceProof() {
      return malfeasanceProof_ == null ? spacemesh.v1.Types.MalfeasanceProof.getDefaultInstance() : malfeasanceProof_;
    }
    /**
     * <code>.spacemesh.v1.MalfeasanceProof malfeasance_proof = 2;</code>
     */
    @java.lang.Override
    public spacemesh.v1.Types.MalfeasanceProofOrBuilder getMalfeasanceProofOrBuilder() {
      return malfeasanceProof_ == null ? spacemesh.v1.Types.MalfeasanceProof.getDefaultInstance() : malfeasanceProof_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getAtx());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getMalfeasanceProof());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getAtx());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getMalfeasanceProof());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof spacemesh.v1.ActivationTypes.GetResponse)) {
        return super.equals(obj);
      }
      spacemesh.v1.ActivationTypes.GetResponse other = (spacemesh.v1.ActivationTypes.GetResponse) obj;

      if (hasAtx() != other.hasAtx()) return false;
      if (hasAtx()) {
        if (!getAtx()
            .equals(other.getAtx())) return false;
      }
      if (hasMalfeasanceProof() != other.hasMalfeasanceProof()) return false;
      if (hasMalfeasanceProof()) {
        if (!getMalfeasanceProof()
            .equals(other.getMalfeasanceProof())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAtx()) {
        hash = (37 * hash) + ATX_FIELD_NUMBER;
        hash = (53 * hash) + getAtx().hashCode();
      }
      if (hasMalfeasanceProof()) {
        hash = (37 * hash) + MALFEASANCE_PROOF_FIELD_NUMBER;
        hash = (53 * hash) + getMalfeasanceProof().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static spacemesh.v1.ActivationTypes.GetResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static spacemesh.v1.ActivationTypes.GetResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static spacemesh.v1.ActivationTypes.GetResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static spacemesh.v1.ActivationTypes.GetResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static spacemesh.v1.ActivationTypes.GetResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static spacemesh.v1.ActivationTypes.GetResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static spacemesh.v1.ActivationTypes.GetResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static spacemesh.v1.ActivationTypes.GetResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static spacemesh.v1.ActivationTypes.GetResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static spacemesh.v1.ActivationTypes.GetResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static spacemesh.v1.ActivationTypes.GetResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static spacemesh.v1.ActivationTypes.GetResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(spacemesh.v1.ActivationTypes.GetResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code spacemesh.v1.GetResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:spacemesh.v1.GetResponse)
        spacemesh.v1.ActivationTypes.GetResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return spacemesh.v1.ActivationTypes.internal_static_spacemesh_v1_GetResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return spacemesh.v1.ActivationTypes.internal_static_spacemesh_v1_GetResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                spacemesh.v1.ActivationTypes.GetResponse.class, spacemesh.v1.ActivationTypes.GetResponse.Builder.class);
      }

      // Construct using spacemesh.v1.ActivationTypes.GetResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAtxFieldBuilder();
          getMalfeasanceProofFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        atx_ = null;
        if (atxBuilder_ != null) {
          atxBuilder_.dispose();
          atxBuilder_ = null;
        }
        malfeasanceProof_ = null;
        if (malfeasanceProofBuilder_ != null) {
          malfeasanceProofBuilder_.dispose();
          malfeasanceProofBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return spacemesh.v1.ActivationTypes.internal_static_spacemesh_v1_GetResponse_descriptor;
      }

      @java.lang.Override
      public spacemesh.v1.ActivationTypes.GetResponse getDefaultInstanceForType() {
        return spacemesh.v1.ActivationTypes.GetResponse.getDefaultInstance();
      }

      @java.lang.Override
      public spacemesh.v1.ActivationTypes.GetResponse build() {
        spacemesh.v1.ActivationTypes.GetResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public spacemesh.v1.ActivationTypes.GetResponse buildPartial() {
        spacemesh.v1.ActivationTypes.GetResponse result = new spacemesh.v1.ActivationTypes.GetResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(spacemesh.v1.ActivationTypes.GetResponse result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.atx_ = atxBuilder_ == null
              ? atx_
              : atxBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.malfeasanceProof_ = malfeasanceProofBuilder_ == null
              ? malfeasanceProof_
              : malfeasanceProofBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof spacemesh.v1.ActivationTypes.GetResponse) {
          return mergeFrom((spacemesh.v1.ActivationTypes.GetResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(spacemesh.v1.ActivationTypes.GetResponse other) {
        if (other == spacemesh.v1.ActivationTypes.GetResponse.getDefaultInstance()) return this;
        if (other.hasAtx()) {
          mergeAtx(other.getAtx());
        }
        if (other.hasMalfeasanceProof()) {
          mergeMalfeasanceProof(other.getMalfeasanceProof());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getAtxFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getMalfeasanceProofFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private spacemesh.v1.Types.Activation atx_;
      private com.google.protobuf.SingleFieldBuilderV3<
          spacemesh.v1.Types.Activation, spacemesh.v1.Types.Activation.Builder, spacemesh.v1.Types.ActivationOrBuilder> atxBuilder_;
      /**
       * <code>.spacemesh.v1.Activation atx = 1;</code>
       * @return Whether the atx field is set.
       */
      public boolean hasAtx() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.spacemesh.v1.Activation atx = 1;</code>
       * @return The atx.
       */
      public spacemesh.v1.Types.Activation getAtx() {
        if (atxBuilder_ == null) {
          return atx_ == null ? spacemesh.v1.Types.Activation.getDefaultInstance() : atx_;
        } else {
          return atxBuilder_.getMessage();
        }
      }
      /**
       * <code>.spacemesh.v1.Activation atx = 1;</code>
       */
      public Builder setAtx(spacemesh.v1.Types.Activation value) {
        if (atxBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          atx_ = value;
        } else {
          atxBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.spacemesh.v1.Activation atx = 1;</code>
       */
      public Builder setAtx(
          spacemesh.v1.Types.Activation.Builder builderForValue) {
        if (atxBuilder_ == null) {
          atx_ = builderForValue.build();
        } else {
          atxBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.spacemesh.v1.Activation atx = 1;</code>
       */
      public Builder mergeAtx(spacemesh.v1.Types.Activation value) {
        if (atxBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            atx_ != null &&
            atx_ != spacemesh.v1.Types.Activation.getDefaultInstance()) {
            getAtxBuilder().mergeFrom(value);
          } else {
            atx_ = value;
          }
        } else {
          atxBuilder_.mergeFrom(value);
        }
        if (atx_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.spacemesh.v1.Activation atx = 1;</code>
       */
      public Builder clearAtx() {
        bitField0_ = (bitField0_ & ~0x00000001);
        atx_ = null;
        if (atxBuilder_ != null) {
          atxBuilder_.dispose();
          atxBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.spacemesh.v1.Activation atx = 1;</code>
       */
      public spacemesh.v1.Types.Activation.Builder getAtxBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getAtxFieldBuilder().getBuilder();
      }
      /**
       * <code>.spacemesh.v1.Activation atx = 1;</code>
       */
      public spacemesh.v1.Types.ActivationOrBuilder getAtxOrBuilder() {
        if (atxBuilder_ != null) {
          return atxBuilder_.getMessageOrBuilder();
        } else {
          return atx_ == null ?
              spacemesh.v1.Types.Activation.getDefaultInstance() : atx_;
        }
      }
      /**
       * <code>.spacemesh.v1.Activation atx = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          spacemesh.v1.Types.Activation, spacemesh.v1.Types.Activation.Builder, spacemesh.v1.Types.ActivationOrBuilder> 
          getAtxFieldBuilder() {
        if (atxBuilder_ == null) {
          atxBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              spacemesh.v1.Types.Activation, spacemesh.v1.Types.Activation.Builder, spacemesh.v1.Types.ActivationOrBuilder>(
                  getAtx(),
                  getParentForChildren(),
                  isClean());
          atx_ = null;
        }
        return atxBuilder_;
      }

      private spacemesh.v1.Types.MalfeasanceProof malfeasanceProof_;
      private com.google.protobuf.SingleFieldBuilderV3<
          spacemesh.v1.Types.MalfeasanceProof, spacemesh.v1.Types.MalfeasanceProof.Builder, spacemesh.v1.Types.MalfeasanceProofOrBuilder> malfeasanceProofBuilder_;
      /**
       * <code>.spacemesh.v1.MalfeasanceProof malfeasance_proof = 2;</code>
       * @return Whether the malfeasanceProof field is set.
       */
      public boolean hasMalfeasanceProof() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.spacemesh.v1.MalfeasanceProof malfeasance_proof = 2;</code>
       * @return The malfeasanceProof.
       */
      public spacemesh.v1.Types.MalfeasanceProof getMalfeasanceProof() {
        if (malfeasanceProofBuilder_ == null) {
          return malfeasanceProof_ == null ? spacemesh.v1.Types.MalfeasanceProof.getDefaultInstance() : malfeasanceProof_;
        } else {
          return malfeasanceProofBuilder_.getMessage();
        }
      }
      /**
       * <code>.spacemesh.v1.MalfeasanceProof malfeasance_proof = 2;</code>
       */
      public Builder setMalfeasanceProof(spacemesh.v1.Types.MalfeasanceProof value) {
        if (malfeasanceProofBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          malfeasanceProof_ = value;
        } else {
          malfeasanceProofBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.spacemesh.v1.MalfeasanceProof malfeasance_proof = 2;</code>
       */
      public Builder setMalfeasanceProof(
          spacemesh.v1.Types.MalfeasanceProof.Builder builderForValue) {
        if (malfeasanceProofBuilder_ == null) {
          malfeasanceProof_ = builderForValue.build();
        } else {
          malfeasanceProofBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.spacemesh.v1.MalfeasanceProof malfeasance_proof = 2;</code>
       */
      public Builder mergeMalfeasanceProof(spacemesh.v1.Types.MalfeasanceProof value) {
        if (malfeasanceProofBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            malfeasanceProof_ != null &&
            malfeasanceProof_ != spacemesh.v1.Types.MalfeasanceProof.getDefaultInstance()) {
            getMalfeasanceProofBuilder().mergeFrom(value);
          } else {
            malfeasanceProof_ = value;
          }
        } else {
          malfeasanceProofBuilder_.mergeFrom(value);
        }
        if (malfeasanceProof_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.spacemesh.v1.MalfeasanceProof malfeasance_proof = 2;</code>
       */
      public Builder clearMalfeasanceProof() {
        bitField0_ = (bitField0_ & ~0x00000002);
        malfeasanceProof_ = null;
        if (malfeasanceProofBuilder_ != null) {
          malfeasanceProofBuilder_.dispose();
          malfeasanceProofBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.spacemesh.v1.MalfeasanceProof malfeasance_proof = 2;</code>
       */
      public spacemesh.v1.Types.MalfeasanceProof.Builder getMalfeasanceProofBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getMalfeasanceProofFieldBuilder().getBuilder();
      }
      /**
       * <code>.spacemesh.v1.MalfeasanceProof malfeasance_proof = 2;</code>
       */
      public spacemesh.v1.Types.MalfeasanceProofOrBuilder getMalfeasanceProofOrBuilder() {
        if (malfeasanceProofBuilder_ != null) {
          return malfeasanceProofBuilder_.getMessageOrBuilder();
        } else {
          return malfeasanceProof_ == null ?
              spacemesh.v1.Types.MalfeasanceProof.getDefaultInstance() : malfeasanceProof_;
        }
      }
      /**
       * <code>.spacemesh.v1.MalfeasanceProof malfeasance_proof = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          spacemesh.v1.Types.MalfeasanceProof, spacemesh.v1.Types.MalfeasanceProof.Builder, spacemesh.v1.Types.MalfeasanceProofOrBuilder> 
          getMalfeasanceProofFieldBuilder() {
        if (malfeasanceProofBuilder_ == null) {
          malfeasanceProofBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              spacemesh.v1.Types.MalfeasanceProof, spacemesh.v1.Types.MalfeasanceProof.Builder, spacemesh.v1.Types.MalfeasanceProofOrBuilder>(
                  getMalfeasanceProof(),
                  getParentForChildren(),
                  isClean());
          malfeasanceProof_ = null;
        }
        return malfeasanceProofBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:spacemesh.v1.GetResponse)
    }

    // @@protoc_insertion_point(class_scope:spacemesh.v1.GetResponse)
    private static final spacemesh.v1.ActivationTypes.GetResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new spacemesh.v1.ActivationTypes.GetResponse();
    }

    public static spacemesh.v1.ActivationTypes.GetResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetResponse>
        PARSER = new com.google.protobuf.AbstractParser<GetResponse>() {
      @java.lang.Override
      public GetResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GetResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public spacemesh.v1.ActivationTypes.GetResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HighestResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:spacemesh.v1.HighestResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.spacemesh.v1.Activation atx = 1;</code>
     * @return Whether the atx field is set.
     */
    boolean hasAtx();
    /**
     * <code>.spacemesh.v1.Activation atx = 1;</code>
     * @return The atx.
     */
    spacemesh.v1.Types.Activation getAtx();
    /**
     * <code>.spacemesh.v1.Activation atx = 1;</code>
     */
    spacemesh.v1.Types.ActivationOrBuilder getAtxOrBuilder();
  }
  /**
   * Protobuf type {@code spacemesh.v1.HighestResponse}
   */
  public static final class HighestResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:spacemesh.v1.HighestResponse)
      HighestResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HighestResponse.newBuilder() to construct.
    private HighestResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HighestResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new HighestResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return spacemesh.v1.ActivationTypes.internal_static_spacemesh_v1_HighestResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return spacemesh.v1.ActivationTypes.internal_static_spacemesh_v1_HighestResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              spacemesh.v1.ActivationTypes.HighestResponse.class, spacemesh.v1.ActivationTypes.HighestResponse.Builder.class);
    }

    private int bitField0_;
    public static final int ATX_FIELD_NUMBER = 1;
    private spacemesh.v1.Types.Activation atx_;
    /**
     * <code>.spacemesh.v1.Activation atx = 1;</code>
     * @return Whether the atx field is set.
     */
    @java.lang.Override
    public boolean hasAtx() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.spacemesh.v1.Activation atx = 1;</code>
     * @return The atx.
     */
    @java.lang.Override
    public spacemesh.v1.Types.Activation getAtx() {
      return atx_ == null ? spacemesh.v1.Types.Activation.getDefaultInstance() : atx_;
    }
    /**
     * <code>.spacemesh.v1.Activation atx = 1;</code>
     */
    @java.lang.Override
    public spacemesh.v1.Types.ActivationOrBuilder getAtxOrBuilder() {
      return atx_ == null ? spacemesh.v1.Types.Activation.getDefaultInstance() : atx_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getAtx());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getAtx());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof spacemesh.v1.ActivationTypes.HighestResponse)) {
        return super.equals(obj);
      }
      spacemesh.v1.ActivationTypes.HighestResponse other = (spacemesh.v1.ActivationTypes.HighestResponse) obj;

      if (hasAtx() != other.hasAtx()) return false;
      if (hasAtx()) {
        if (!getAtx()
            .equals(other.getAtx())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAtx()) {
        hash = (37 * hash) + ATX_FIELD_NUMBER;
        hash = (53 * hash) + getAtx().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static spacemesh.v1.ActivationTypes.HighestResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static spacemesh.v1.ActivationTypes.HighestResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static spacemesh.v1.ActivationTypes.HighestResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static spacemesh.v1.ActivationTypes.HighestResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static spacemesh.v1.ActivationTypes.HighestResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static spacemesh.v1.ActivationTypes.HighestResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static spacemesh.v1.ActivationTypes.HighestResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static spacemesh.v1.ActivationTypes.HighestResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static spacemesh.v1.ActivationTypes.HighestResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static spacemesh.v1.ActivationTypes.HighestResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static spacemesh.v1.ActivationTypes.HighestResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static spacemesh.v1.ActivationTypes.HighestResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(spacemesh.v1.ActivationTypes.HighestResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code spacemesh.v1.HighestResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:spacemesh.v1.HighestResponse)
        spacemesh.v1.ActivationTypes.HighestResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return spacemesh.v1.ActivationTypes.internal_static_spacemesh_v1_HighestResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return spacemesh.v1.ActivationTypes.internal_static_spacemesh_v1_HighestResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                spacemesh.v1.ActivationTypes.HighestResponse.class, spacemesh.v1.ActivationTypes.HighestResponse.Builder.class);
      }

      // Construct using spacemesh.v1.ActivationTypes.HighestResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAtxFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        atx_ = null;
        if (atxBuilder_ != null) {
          atxBuilder_.dispose();
          atxBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return spacemesh.v1.ActivationTypes.internal_static_spacemesh_v1_HighestResponse_descriptor;
      }

      @java.lang.Override
      public spacemesh.v1.ActivationTypes.HighestResponse getDefaultInstanceForType() {
        return spacemesh.v1.ActivationTypes.HighestResponse.getDefaultInstance();
      }

      @java.lang.Override
      public spacemesh.v1.ActivationTypes.HighestResponse build() {
        spacemesh.v1.ActivationTypes.HighestResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public spacemesh.v1.ActivationTypes.HighestResponse buildPartial() {
        spacemesh.v1.ActivationTypes.HighestResponse result = new spacemesh.v1.ActivationTypes.HighestResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(spacemesh.v1.ActivationTypes.HighestResponse result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.atx_ = atxBuilder_ == null
              ? atx_
              : atxBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof spacemesh.v1.ActivationTypes.HighestResponse) {
          return mergeFrom((spacemesh.v1.ActivationTypes.HighestResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(spacemesh.v1.ActivationTypes.HighestResponse other) {
        if (other == spacemesh.v1.ActivationTypes.HighestResponse.getDefaultInstance()) return this;
        if (other.hasAtx()) {
          mergeAtx(other.getAtx());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getAtxFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private spacemesh.v1.Types.Activation atx_;
      private com.google.protobuf.SingleFieldBuilderV3<
          spacemesh.v1.Types.Activation, spacemesh.v1.Types.Activation.Builder, spacemesh.v1.Types.ActivationOrBuilder> atxBuilder_;
      /**
       * <code>.spacemesh.v1.Activation atx = 1;</code>
       * @return Whether the atx field is set.
       */
      public boolean hasAtx() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.spacemesh.v1.Activation atx = 1;</code>
       * @return The atx.
       */
      public spacemesh.v1.Types.Activation getAtx() {
        if (atxBuilder_ == null) {
          return atx_ == null ? spacemesh.v1.Types.Activation.getDefaultInstance() : atx_;
        } else {
          return atxBuilder_.getMessage();
        }
      }
      /**
       * <code>.spacemesh.v1.Activation atx = 1;</code>
       */
      public Builder setAtx(spacemesh.v1.Types.Activation value) {
        if (atxBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          atx_ = value;
        } else {
          atxBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.spacemesh.v1.Activation atx = 1;</code>
       */
      public Builder setAtx(
          spacemesh.v1.Types.Activation.Builder builderForValue) {
        if (atxBuilder_ == null) {
          atx_ = builderForValue.build();
        } else {
          atxBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.spacemesh.v1.Activation atx = 1;</code>
       */
      public Builder mergeAtx(spacemesh.v1.Types.Activation value) {
        if (atxBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            atx_ != null &&
            atx_ != spacemesh.v1.Types.Activation.getDefaultInstance()) {
            getAtxBuilder().mergeFrom(value);
          } else {
            atx_ = value;
          }
        } else {
          atxBuilder_.mergeFrom(value);
        }
        if (atx_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.spacemesh.v1.Activation atx = 1;</code>
       */
      public Builder clearAtx() {
        bitField0_ = (bitField0_ & ~0x00000001);
        atx_ = null;
        if (atxBuilder_ != null) {
          atxBuilder_.dispose();
          atxBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.spacemesh.v1.Activation atx = 1;</code>
       */
      public spacemesh.v1.Types.Activation.Builder getAtxBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getAtxFieldBuilder().getBuilder();
      }
      /**
       * <code>.spacemesh.v1.Activation atx = 1;</code>
       */
      public spacemesh.v1.Types.ActivationOrBuilder getAtxOrBuilder() {
        if (atxBuilder_ != null) {
          return atxBuilder_.getMessageOrBuilder();
        } else {
          return atx_ == null ?
              spacemesh.v1.Types.Activation.getDefaultInstance() : atx_;
        }
      }
      /**
       * <code>.spacemesh.v1.Activation atx = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          spacemesh.v1.Types.Activation, spacemesh.v1.Types.Activation.Builder, spacemesh.v1.Types.ActivationOrBuilder> 
          getAtxFieldBuilder() {
        if (atxBuilder_ == null) {
          atxBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              spacemesh.v1.Types.Activation, spacemesh.v1.Types.Activation.Builder, spacemesh.v1.Types.ActivationOrBuilder>(
                  getAtx(),
                  getParentForChildren(),
                  isClean());
          atx_ = null;
        }
        return atxBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:spacemesh.v1.HighestResponse)
    }

    // @@protoc_insertion_point(class_scope:spacemesh.v1.HighestResponse)
    private static final spacemesh.v1.ActivationTypes.HighestResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new spacemesh.v1.ActivationTypes.HighestResponse();
    }

    public static spacemesh.v1.ActivationTypes.HighestResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HighestResponse>
        PARSER = new com.google.protobuf.AbstractParser<HighestResponse>() {
      @java.lang.Override
      public HighestResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<HighestResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HighestResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public spacemesh.v1.ActivationTypes.HighestResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spacemesh_v1_GetRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spacemesh_v1_GetRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spacemesh_v1_GetResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spacemesh_v1_GetResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spacemesh_v1_HighestResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spacemesh_v1_HighestResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#spacemesh/v1/activation_types.proto\022\014s" +
      "pacemesh.v1\032\030spacemesh/v1/types.proto\"\030\n" +
      "\nGetRequest\022\n\n\002id\030\001 \001(\014\"o\n\013GetResponse\022%" +
      "\n\003atx\030\001 \001(\0132\030.spacemesh.v1.Activation\0229\n" +
      "\021malfeasance_proof\030\002 \001(\0132\036.spacemesh.v1." +
      "MalfeasanceProof\"8\n\017HighestResponse\022%\n\003a" +
      "tx\030\001 \001(\0132\030.spacemesh.v1.Activationb\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          spacemesh.v1.Types.getDescriptor(),
        });
    internal_static_spacemesh_v1_GetRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_spacemesh_v1_GetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spacemesh_v1_GetRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_spacemesh_v1_GetResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_spacemesh_v1_GetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spacemesh_v1_GetResponse_descriptor,
        new java.lang.String[] { "Atx", "MalfeasanceProof", });
    internal_static_spacemesh_v1_HighestResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_spacemesh_v1_HighestResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spacemesh_v1_HighestResponse_descriptor,
        new java.lang.String[] { "Atx", });
    spacemesh.v1.Types.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
