// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spacemesh/v1/activation.proto

// Protobuf Java Version: 3.25.1
package spacemesh.v1;

public final class Activation {
  private Activation() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035spacemesh/v1/activation.proto\022\014spaceme" +
      "sh.v1\032\033google/protobuf/empty.proto\032#spac" +
      "emesh/v1/activation_types.proto2\221\001\n\021Acti" +
      "vationService\022:\n\003Get\022\030.spacemesh.v1.GetR" +
      "equest\032\031.spacemesh.v1.GetResponse\022@\n\007Hig" +
      "hest\022\026.google.protobuf.Empty\032\035.spacemesh" +
      ".v1.HighestResponseb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          spacemesh.v1.ActivationTypes.getDescriptor(),
        });
    com.google.protobuf.EmptyProto.getDescriptor();
    spacemesh.v1.ActivationTypes.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
