// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spacemesh/v1/admin.proto

// Protobuf Java Version: 3.25.1
package spacemesh.v1;

public final class Admin {
  private Admin() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030spacemesh/v1/admin.proto\022\014spacemesh.v1" +
      "\032\033google/protobuf/empty.proto\032\036spacemesh" +
      "/v1/admin_types.proto2\301\002\n\014AdminService\022c" +
      "\n\020CheckpointStream\022%.spacemesh.v1.Checkp" +
      "ointStreamRequest\032&.spacemesh.v1.Checkpo" +
      "intStreamResponse0\001\022?\n\007Recover\022\034.spaceme" +
      "sh.v1.RecoverRequest\032\026.google.protobuf.E" +
      "mpty\022G\n\014EventsStream\022 .spacemesh.v1.Even" +
      "tStreamRequest\032\023.spacemesh.v1.Event0\001\022B\n" +
      "\016PeerInfoStream\022\026.google.protobuf.Empty\032" +
      "\026.spacemesh.v1.PeerInfo0\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          spacemesh.v1.AdminTypes.getDescriptor(),
        });
    com.google.protobuf.EmptyProto.getDescriptor();
    spacemesh.v1.AdminTypes.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
