// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spacemesh/v1/mesh.proto

// Protobuf Java Version: 3.25.1
package spacemesh.v1;

public final class Mesh {
  private Mesh() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027spacemesh/v1/mesh.proto\022\014spacemesh.v1\032" +
      "\034google/api/annotations.proto\032\035spacemesh" +
      "/v1/mesh_types.proto2\371\014\n\013MeshService\022s\n\013" +
      "GenesisTime\022 .spacemesh.v1.GenesisTimeRe" +
      "quest\032!.spacemesh.v1.GenesisTimeResponse" +
      "\"\037\202\323\344\223\002\031\"\024/v1/mesh/genesistime:\001*\022w\n\014Cur" +
      "rentLayer\022!.spacemesh.v1.CurrentLayerReq" +
      "uest\032\".spacemesh.v1.CurrentLayerResponse" +
      "\" \202\323\344\223\002\032\"\025/v1/mesh/currentlayer:\001*\022w\n\014Cu" +
      "rrentEpoch\022!.spacemesh.v1.CurrentEpochRe" +
      "quest\032\".spacemesh.v1.CurrentEpochRespons" +
      "e\" \202\323\344\223\002\032\"\025/v1/mesh/currentepoch:\001*\022k\n\tG" +
      "enesisID\022\036.spacemesh.v1.GenesisIDRequest" +
      "\032\037.spacemesh.v1.GenesisIDResponse\"\035\202\323\344\223\002" +
      "\027\"\022/v1/mesh/genesisid:\001*\022\177\n\016EpochNumLaye" +
      "rs\022#.spacemesh.v1.EpochNumLayersRequest\032" +
      "$.spacemesh.v1.EpochNumLayersResponse\"\"\202" +
      "\323\344\223\002\034\"\027/v1/mesh/epochnumlayers:\001*\022{\n\rLay" +
      "erDuration\022\".spacemesh.v1.LayerDurationR" +
      "equest\032#.spacemesh.v1.LayerDurationRespo" +
      "nse\"!\202\323\344\223\002\033\"\026/v1/mesh/layerduration:\001*\022\247" +
      "\001\n\030MaxTransactionsPerSecond\022-.spacemesh." +
      "v1.MaxTransactionsPerSecondRequest\032..spa" +
      "cemesh.v1.MaxTransactionsPerSecondRespon" +
      "se\",\202\323\344\223\002&\"!/v1/mesh/maxtransactionspers" +
      "econd:\001*\022\227\001\n\024AccountMeshDataQuery\022).spac" +
      "emesh.v1.AccountMeshDataQueryRequest\032*.s" +
      "pacemesh.v1.AccountMeshDataQueryResponse" +
      "\"(\202\323\344\223\002\"\"\035/v1/mesh/accountmeshdataquery:" +
      "\001*\022s\n\013LayersQuery\022 .spacemesh.v1.LayersQ" +
      "ueryRequest\032!.spacemesh.v1.LayersQueryRe" +
      "sponse\"\037\202\323\344\223\002\031\"\024/v1/mesh/layersquery:\001*\022" +
      "r\n\025AccountMeshDataStream\022*.spacemesh.v1." +
      "AccountMeshDataStreamRequest\032+.spacemesh" +
      ".v1.AccountMeshDataStreamResponse0\001\022T\n\013L" +
      "ayerStream\022 .spacemesh.v1.LayerStreamReq" +
      "uest\032!.spacemesh.v1.LayerStreamResponse0" +
      "\001\022T\n\013EpochStream\022 .spacemesh.v1.EpochStr" +
      "eamRequest\032!.spacemesh.v1.EpochStreamRes" +
      "ponse0\001\022W\n\020MalfeasanceQuery\022 .spacemesh." +
      "v1.MalfeasanceRequest\032!.spacemesh.v1.Mal" +
      "feasanceResponse\022f\n\021MalfeasanceStream\022&." +
      "spacemesh.v1.MalfeasanceStreamRequest\032\'." +
      "spacemesh.v1.MalfeasanceStreamResponse0\001" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          spacemesh.v1.MeshTypes.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    spacemesh.v1.MeshTypes.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
