// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spacemesh/v1/post.proto

// Protobuf Java Version: 3.25.1
package spacemesh.v1;

public final class Post {
  private Post() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027spacemesh/v1/post.proto\022\014spacemesh.v1\032" +
      "\035spacemesh/v1/post_types.proto2W\n\013PostSe" +
      "rvice\022H\n\010Register\022\035.spacemesh.v1.Service" +
      "Response\032\031.spacemesh.v1.NodeRequest(\0010\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          spacemesh.v1.PostTypes.getDescriptor(),
        });
    spacemesh.v1.PostTypes.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
