// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spacemesh/v1/smesher.proto

// Protobuf Java Version: 3.25.1
package spacemesh.v1;

public final class Smesher {
  private Smesher() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032spacemesh/v1/smesher.proto\022\014spacemesh." +
      "v1\032\034google/api/annotations.proto\032\033google" +
      "/protobuf/empty.proto\032 spacemesh/v1/smes" +
      "her_types.proto2\343\013\n\016SmesherService\022f\n\nIs" +
      "Smeshing\022\026.google.protobuf.Empty\032 .space" +
      "mesh.v1.IsSmeshingResponse\"\036\202\323\344\223\002\030\"\026/v1/" +
      "smesher/issmeshing\022~\n\rStartSmeshing\022\".sp" +
      "acemesh.v1.StartSmeshingRequest\032#.spacem" +
      "esh.v1.StartSmeshingResponse\"$\202\323\344\223\002\036\"\031/v" +
      "1/smesher/startsmeshing:\001*\022z\n\014StopSmeshi" +
      "ng\022!.spacemesh.v1.StopSmeshingRequest\032\"." +
      "spacemesh.v1.StopSmeshingResponse\"#\202\323\344\223\002" +
      "\035\"\030/v1/smesher/stopsmeshing:\001*\022c\n\tSmeshe" +
      "rID\022\026.google.protobuf.Empty\032\037.spacemesh." +
      "v1.SmesherIDResponse\"\035\202\323\344\223\002\027\"\025/v1/smeshe" +
      "r/smesherid\022`\n\010Coinbase\022\026.google.protobu" +
      "f.Empty\032\036.spacemesh.v1.CoinbaseResponse\"" +
      "\034\202\323\344\223\002\026\"\024/v1/smesher/coinbase\022v\n\013SetCoin" +
      "base\022 .spacemesh.v1.SetCoinbaseRequest\032!" +
      ".spacemesh.v1.SetCoinbaseResponse\"\"\202\323\344\223\002" +
      "\034\"\027/v1/smesher/setcoinbase:\001*\022Z\n\006MinGas\022" +
      "\026.google.protobuf.Empty\032\034.spacemesh.v1.M" +
      "inGasResponse\"\032\202\323\344\223\002\024\"\022/v1/smesher/minga" +
      "s\022n\n\tSetMinGas\022\036.spacemesh.v1.SetMinGasR" +
      "equest\032\037.spacemesh.v1.SetMinGasResponse\"" +
      " \202\323\344\223\002\032\"\025/v1/smesher/setmingas:\001*\022\212\001\n\020Es" +
      "timatedRewards\022%.spacemesh.v1.EstimatedR" +
      "ewardsRequest\032&.spacemesh.v1.EstimatedRe" +
      "wardsResponse\"\'\202\323\344\223\002!\"\034/v1/smesher/estim" +
      "atedrewards:\001*\022u\n\017PostSetupStatus\022\026.goog" +
      "le.protobuf.Empty\032%.spacemesh.v1.PostSet" +
      "upStatusResponse\"#\202\323\344\223\002\035\"\033/v1/smesher/po" +
      "stsetupstatus\022^\n\025PostSetupStatusStream\022\026" +
      ".google.protobuf.Empty\032+.spacemesh.v1.Po" +
      "stSetupStatusStreamResponse0\001\022\222\001\n\022PostSe" +
      "tupProviders\022\'.spacemesh.v1.PostSetupPro" +
      "vidersRequest\032(.spacemesh.v1.PostSetupPr" +
      "ovidersResponse\")\202\323\344\223\002#\"\036/v1/smesher/pos" +
      "tsetupproviders:\001*\022i\n\nPostConfig\022\026.googl" +
      "e.protobuf.Empty\032 .spacemesh.v1.PostConf" +
      "igResponse\"!\202\323\344\223\002\033\"\026/v1/smesher/postconf" +
      "ig:\001*b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
          spacemesh.v1.SmesherTypes.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
    spacemesh.v1.SmesherTypes.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
