// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spacemesh/v1/tx.proto

// Protobuf Java Version: 3.25.1
package spacemesh.v1;

public final class Tx {
  private Tx() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025spacemesh/v1/tx.proto\022\014spacemesh.v1\032\034g" +
      "oogle/api/annotations.proto\032\033spacemesh/v" +
      "1/tx_types.proto2\370\004\n\022TransactionService\022" +
      "\222\001\n\021SubmitTransaction\022&.spacemesh.v1.Sub" +
      "mitTransactionRequest\032\'.spacemesh.v1.Sub" +
      "mitTransactionResponse\",\202\323\344\223\002&\"!/v1/tran" +
      "saction/submittransaction:\001*\022a\n\020ParseTra" +
      "nsaction\022%.spacemesh.v1.ParseTransaction" +
      "Request\032&.spacemesh.v1.ParseTransactionR" +
      "esponse\022\222\001\n\021TransactionsState\022&.spacemes" +
      "h.v1.TransactionsStateRequest\032\'.spacemes" +
      "h.v1.TransactionsStateResponse\",\202\323\344\223\002&\"!" +
      "/v1/transaction/transactionsstate:\001*\022x\n\027" +
      "TransactionsStateStream\022,.spacemesh.v1.T" +
      "ransactionsStateStreamRequest\032-.spacemes" +
      "h.v1.TransactionsStateStreamResponse0\001\022[" +
      "\n\rStreamResults\022\'.spacemesh.v1.Transacti" +
      "onResultsRequest\032\037.spacemesh.v1.Transact" +
      "ionResult0\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          spacemesh.v1.TxTypes.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    spacemesh.v1.TxTypes.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
